name: music_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  go_router: ^16.0.0
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  get: ^4.7.2
  equatable: ^2.0.7
  flutter_pretty_dio_logger: ^3.0.0
  connectivity_plus: ^6.1.4
  hive: ^2.2.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.0
  foundation: ^0.0.5
  just_audio: ^0.10.0
  audio_metadata_reader: ^1.4.1
  path_provider: ^2.1.5
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  flutter_blue_plus: ^1.32.9
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1
  lottie: ^3.3.1
  volume_controller: ^3.3.0
  pdf: ^3.11.3
  printing: ^5.14.2
  provider: ^6.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
